#!/usr/bin/env bash
# Author: Fuat Bölük <mektup@fuatboluk.com.tr>

curl -s https://www.usom.gov.tr/url-list.txt -o /tmp/url-list.txt

start=$(date "+%H:%M:%S")

echo
echo "Start time      : $start"
echo "Description     : USOM malicious ip addresses and domains blacklist!"
echo "Original url    : https://www.usom.gov.tr/url-list.txt"
echo
echo
echo "## Listing all active malicious ips..."
echo

grep "/" /tmp/url-list.txt | cut -d "/" -f 1 | sort | \
grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | cut -d ":" -f 1 | uniq >/tmp/ip-blacklist.txt

while read -r ip; do
    if [ -n "$ip" ]; then
        control=$(timeout --foreground 5s curl -Is "$ip" --connect-timeout 5 | grep "HTTP")
        if [ -n "$control" ]; then
            echo "$ip" >>/tmp/all-ip-blacklist.txt
            echo "  Connected     : $ip"
        else
            echo "  Not connected : $ip"
        fi
    fi
done <<<"$(cat /tmp/ip-blacklist.txt)"

rm -f /tmp/ip-blacklist.txt

echo
echo
echo "## Listing all active malicious domains..."
echo

grep "/" /tmp/url-list.txt | cut -d "/" -f 1 | sort | \
sed -e "s|www\.||" | cut -d ":" -f 1 | uniq | grep -v "^[0-9].*" | grep -v "^t.co$" >/tmp/domain-blacklist.txt

while read -r domain; do
    if [ -n "$domain" ]; then
        control=$(timeout --foreground 5s curl -Is "$domain" --connect-timeout 5 | grep "HTTP")
        if [ -n "$control" ]; then
            echo "$domain" >>/tmp/all-domain-blacklist.txt
            echo "  Connected     : $domain"
        else
            echo "  Not connected : $domain"
        fi
    fi
done <<<"$(cat /tmp/domain-blacklist.txt)"

rm -f /tmp/domain-blacklist.txt

sort /tmp/all-ip-blacklist.txt | uniq >"$(pwd)/ip-blacklist.txt"
tr "[:upper:]" "[:lower:]" </tmp/all-domain-blacklist.txt | sort | uniq >"$(pwd)/domain-blacklist.txt"

echo
echo
echo "## All malicious ip addresses and domains blacklisted!"
echo
echo "  $(pwd)/ip-blacklist.txt"
echo "  $(pwd)/domain-blacklist.txt"
echo

while read -r host; do
    if [ -n "$host" ]; then
        echo -e "255.255.255.255\t\t$host" >>/tmp/etc-hosts.txt
    fi
done <<<"$(cat /tmp/all-ip-blacklist.txt /tmp/all-domain-blacklist.txt)"

echo "## USOM malicious ip addresses and domains blacklist!" >"$(pwd)/etc-hosts.txt"
echo "## Original url : https://www.usom.gov.tr/url-list.txt" >>"$(pwd)/etc-hosts.txt"
echo "" >>"$(pwd)/etc-hosts.txt"

cat /tmp/etc-hosts.txt >>"$(pwd)/etc-hosts.txt"

while read -r unbound; do
    if [ -n "$unbound" ]; then
        echo "local-zone: \"$unbound\" redirect" >>/tmp/unbound-conf.txt
        echo "local-data: \"$unbound A 255.255.255.255\"" >>/tmp/unbound-conf.txt
    fi
done <<<"$(cat /tmp/all-domain-blacklist.txt)"

echo "## USOM malicious ip addresses and domains blacklist!" >"$(pwd)/unbound-conf.txt"
echo "## Original url : https://www.usom.gov.tr/url-list.txt" >>"$(pwd)/unbound-conf.txt"
echo "" >>"$(pwd)/unbound-conf.txt"

cat /tmp/unbound-conf.txt >>"$(pwd)/unbound-conf.txt"

echo
echo "## Local blacklists created!"
echo
echo "  $(pwd)/etc-hosts.txt"
echo "  $(pwd)/unbound-conf.txt"
echo

rm -f /tmp/all-ip-blacklist.txt /tmp/all-domain-blacklist.txt /tmp/etc-hosts.txt /tmp/unbound-conf.txt

end=$(date "+%H:%M:%S")
elapsed=$(($(date -d "$end" +%s) - $(date -d "$start" +%s)))

echo
echo "End time        : $end"
echo "Elapsed time    : $(date -d @$elapsed -u +%H:%M:%S)"
echo
echo "Completed!"
echo

# End
